---
title: "ame_installation"
author: "Jesslyn Jesslyn"
date: "2025-06-25"
output: html_document
---

# Installation of RStudio Server in Ubuntun (WSL)
-  steps in: https://posit.co/download/rstudio-server/
Use Ubuntun Packages for R

-  mount windows file
In WSL, run the following:
```{wsl}
/mnt/c/Users/Jesslyn/OneDrive/Desktop
```

# Installation of necessary packages
In WSL terminal:

```{bash}
# install system libraries
sudo apt update
sudo apt install -y \
  build-essential \
  libssl-dev \
  libcurl4-openssl-dev \
  libxml2-dev \
  libfontconfig1-dev \
  libfreetype6-dev \
  libpng-dev \
  libtiff5-dev \
  libjpeg-dev \
  zlib1g-dev \
  libreadline-dev \
  libbz2-dev \
  liblzma-dev \
  libncurses5-dev \
  libx11-dev \
  libxt-dev \
  libzstd-dev \
  libgit2-dev \
  libgsl-dev \
  libglpk-dev \
  libhdf5-dev \
  libharfbuzz-dev \
  libfribidi-dev \
  libtbb-dev \
  libffi-dev \
  cmake \
  git


sudo apt update
sudo apt install build-essential zlib1g-dev libbz2-dev liblzma-dev libcurl4-openssl-dev libssl-dev

# check java works
java -version
```

Accessing R in WSL: R
Closing R in WSL: q()

Start R, then run following code in R:
skip sechm installation cause need v8 which is not available in Ubuntun 24
```{r}
install.packages(c("gsl","ggplot2","remotes","rmarkdown","UpSetR"))

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

pkgs <- c("GenomicRanges", "rtracklayer", "EnrichedHeatmap", "AnnotationHub", 
          "ensembldb", "edgeR", "esATAC", "motifmatchr", "rGREAT",
          "bsseq", "DMRcate", "data.table", "InteractionSet", "limma",
          "universalmotif", "MotifDb", "TFBSTools", "Biostrings", "PWMEnrich",
          "Rsubread", "Rfastp")

BiocManager::install(pkgs, ask = FALSE)

BiocManager::install(c("Bioconductor/BiocFileCache", "chromVAR"))
BiocManager::install("ETHZ-INS/epiwraps")

# check what works
installed <- pkgs %in% rownames(installed.packages())
failed <- pkgs[!installed]
failed
```

# meme set up
Ensure Perl istalled:

Install meme suite:
https://meme-suite.org/meme/doc/install.html?man_type=web#quick_src
- Obtain latest meme file from: https://meme-suite.org/meme/doc/download.html
```{wsl}
wget link_from_above
tar zxf meme-5.5.8.tar.gz # adjust version accordingly
cd meme-5.5.8
```

Check for prerequisite:
```{wsl}
cd scripts
perl dependencies.pl
```
If got issue, check prerequisite setup:
https://meme-suite.org/meme/doc/install.html?man_type=web#prerequisite


```{wsl}
./configure --prefix=$HOME/meme --enable-build-libxml2 --enable-build-libxslt
make
make test
make install
export PATH=$HOME/meme/bin:$HOME/meme/libexec/meme-5.5.8:$PATH
```

After prerequisite setup done:
```{wsl}
make clear
./configure --prefix=$HOME/meme --enable-build-libxml2 --enable-build-libxslt
make
make test
make install
```

# Opening RStudio Server
In WSL terminal, run the following:
```{wsl}
sudo rstudio-server start
```

To get username, run the following in WSL:
```{wsl}
whoami
```

To access mounted folder into WSL, run the following in RStudio Server:
```{wsl}
# can create a script in the home folder so that can run this whenever need to access mounted folder
setwd("/mnt/c/Users/Jesslyn/OneDrive/Desktop") # change accordingly to the mounted folder
```

To run meme functions, make sure to indicate the meme_path as "/home/jesslyn/meme/bin" if needed:
```{wsl}
# example
ame <- memes::runAme(peak_seqs, database=convert_motifs(motifs), meme_path="/home/jesslyn/meme/bin")
```

To stop RStudio server:
```{wsl}
sudo rstudio-server stop
```

Accessing RStudio Server in chrome:

http://localhost:8787/

